### ISSUE TITLE
[User]: Nombre en mayúscula

### ISSUE THREAD

**Issue by AngelicaGuaman** [AngelicaGuaman/IWVG.SwC.AngelicaGuaman#2]
Descripción de la tarea [aquí](https://github.com/AngelicaGuaman/IWVG.SwC.AngelicaGuaman/wiki)

**Comment by rrocamar** [comment]
Hola Angelica!! Me iba a poner con el ticket de la primera entrega, pero me acabo de dar cuenta que en la rama develop ya están incorporados los cambios de la segunda entrega. Cómo lo solucionamos?

**Comment by AngelicaGuaman** [comment]
Hola Ramón. 
No pasa nada, las fechas de entregas son orientativas. Puedes crear tu rama a partir de la rama de develop. Recuerda ejecutar los test y verificar que todo funcione correctamente.
